package za.co.handyflow.platform.clinic.domain.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import za.co.handyflow.platform.shared.TenantId;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "clinic_patients")
@Getter
@NoArgsConstructor
public class ClinicPatient {

    // WHY no @Setter on @Id fields?
    // id, tenantId and createdAt are identity/audit fields that must never
    // change after creation. @Getter only keeps them read-only everywhere.
    // Mutable fields get individual @Setter annotations below.
    @Id UUID id;
    @Column(name = "tenant_id")     UUID      tenantId;
    @Column(name = "first_name")    String    firstName;
    @Column(name = "last_name")     String    lastName;
    @Column(name = "full_name", insertable = false, updatable = false)
    String fullName;                                   // GENERATED ALWAYS column
    @Column(name = "id_number")     String    idNumber;
    @Column(name = "date_of_birth") LocalDate dateOfBirth;
    String gender;
    String phone;
    String email;
    @Column(name = "blood_type")    String    bloodType;

    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "allergies", columnDefinition = "text[]")
    List<String> allergies;

    @JdbcTypeCode(SqlTypes.ARRAY)
    @Column(name = "chronic_conditions", columnDefinition = "text[]")
    List<String> chronicConditions;

    @Column(name = "emergency_contact_name")  String emergencyContactName;
    @Column(name = "emergency_contact_phone") String emergencyContactPhone;
    String notes;

    @Setter boolean active = true;

    @Column(name = "created_at")         Instant createdAt;
    @Column(name = "updated_at") @Setter Instant updatedAt;
    @Column(name = "deleted_at")         Instant deletedAt;
    @Column(name = "deleted_by")         UUID    deletedBy;
    @Version long version;

    // ── P5: Family account fields (added by V81 migration) ───────────────────

    @Setter @Column(name = "principal_id")
    UUID principalId;       // null = INDIVIDUAL or PRINCIPAL root

    @Setter @Column(name = "relationship")
    String relationship;    // CHILD | PARENT | GRANDPARENT | SPOUSE | SIBLING | OTHER

    @Setter @Column(name = "account_type", nullable = false)
    String accountType = "INDIVIDUAL";

    @Setter @Column(name = "archived_at")
    Instant archivedAt;     // null = active; non-null = HPCSA-compliant soft archive

    @Setter @Column(name = "archive_reason")
    String archiveReason;

    @Setter @Column(name = "last_visit_at")
    Instant lastVisitAt;    // denormalised — updated on each createConsultation()

    // NOTE: getId() is generated by @Getter and returns UUID directly.
    // Do NOT add a custom getId() or PatientId wrapper — that breaks all
    // Map<UUID,String> collectors in ClinicService.

    // ── Factory ───────────────────────────────────────────────────────────────

    public static ClinicPatient create(TenantId tenantId,
                                       String firstName, String lastName,
                                       String idNumber, LocalDate dateOfBirth,
                                       String gender, String phone, String email,
                                       String emergencyContactName,
                                       String emergencyContactPhone) {
        ClinicPatient p = new ClinicPatient();
        p.id                    = UUID.randomUUID();
        p.tenantId              = tenantId.getValue();
        p.firstName             = firstName;
        p.lastName              = lastName;
        p.idNumber              = idNumber;
        p.dateOfBirth           = dateOfBirth;
        p.gender                = gender;
        p.phone                 = phone;
        p.email                 = email;
        p.emergencyContactName  = emergencyContactName;
        p.emergencyContactPhone = emergencyContactPhone;
        p.accountType           = "INDIVIDUAL";
        p.active                = true;
        p.createdAt             = Instant.now();
        p.updatedAt             = Instant.now();
        return p;
    }

    // ── Mutators ──────────────────────────────────────────────────────────────

    public void update(String phone, String email,
                       String emergencyContactName, String emergencyContactPhone,
                       String bloodType, List<String> allergies,
                       List<String> chronicConditions, String notes) {
        if (phone                 != null) this.phone                 = phone;
        if (email                 != null) this.email                 = email;
        if (emergencyContactName  != null) this.emergencyContactName  = emergencyContactName;
        if (emergencyContactPhone != null) this.emergencyContactPhone = emergencyContactPhone;
        if (bloodType             != null) this.bloodType             = bloodType;
        if (allergies             != null) this.allergies             = allergies;
        if (chronicConditions     != null) this.chronicConditions     = chronicConditions;
        if (notes                 != null) this.notes                 = notes;
        this.updatedAt = Instant.now();
    }

    public void softDelete(UUID deletedBy) {
        this.deletedAt = Instant.now();
        this.deletedBy = deletedBy;
        this.active    = false;
        this.updatedAt = Instant.now();
    }
}
