-- Clinic permission catalogue (patch 0148): one permission per capability instead of one per module.
-- Behaviour-preserving: every role that held a coarse permission (CLINIC_READ, CLINIC_WRITE, CLINIC_CLINICAL_WRITE,
-- CLINIC_CLINICAL_SIGN, CLINIC_PRESCRIPTION_WRITE, CLINIC_LAB_WRITE, CLINIC_BILLING_READ/WRITE, CLINIC_ADMIN) is given
-- every catalogue permission that replaces what that coarse permission allowed, so endpoints keep working for everyone
-- who could use them before. The coarse permissions stay granted.
-- Never granted automatically: break-glass and restricted-record permissions, bill adjustment, payment allocation and
-- reversal, write-off, claim correction/reversal/resubmission. A practice assigns them to named people.
-- Users must sign out and in once: permissions travel in the sign-in token.

INSERT INTO permissions (id, name, description) VALUES
    (gen_random_uuid(), 'CLINIC_PATIENT_ACCESS', 'Open a patient''s record (context rules such as care relationship and restricted records apply)'),
    (gen_random_uuid(), 'CLINIC_PATIENT_READ', 'Search and view patients'),
    (gen_random_uuid(), 'CLINIC_PATIENT_CREATE', 'Register a patient'),
    (gen_random_uuid(), 'CLINIC_PATIENT_UPDATE', 'Edit a patient''s registration details'),
    (gen_random_uuid(), 'CLINIC_PATIENT_ARCHIVE', 'Archive a patient record'),
    (gen_random_uuid(), 'CLINIC_PATIENT_MERGE', 'Merge duplicate patient records'),
    (gen_random_uuid(), 'CLINIC_PATIENT_DUPLICATE_REVIEW', 'Review and resolve possible duplicate patients'),
    (gen_random_uuid(), 'CLINIC_PATIENT_DEMOGRAPHICS_READ', 'View name, date of birth, sex and ID number'),
    (gen_random_uuid(), 'CLINIC_PATIENT_DEMOGRAPHICS_WRITE', 'Change name, date of birth, sex and ID number'),
    (gen_random_uuid(), 'CLINIC_PATIENT_CONTACT_READ', 'View phone and email'),
    (gen_random_uuid(), 'CLINIC_PATIENT_CONTACT_WRITE', 'Change phone and email'),
    (gen_random_uuid(), 'CLINIC_PATIENT_ADDRESS_READ', 'View addresses'),
    (gen_random_uuid(), 'CLINIC_PATIENT_ADDRESS_WRITE', 'Change addresses'),
    (gen_random_uuid(), 'CLINIC_PATIENT_RELATIONSHIP_READ', 'View family and guarantor relationships'),
    (gen_random_uuid(), 'CLINIC_PATIENT_RELATIONSHIP_WRITE', 'Change family and guarantor relationships'),
    (gen_random_uuid(), 'CLINIC_PATIENT_EMERGENCY_CONTACT_READ', 'View emergency contacts'),
    (gen_random_uuid(), 'CLINIC_PATIENT_EMERGENCY_CONTACT_WRITE', 'Change emergency contacts'),
    (gen_random_uuid(), 'CLINIC_CLINICAL_SUMMARY_READ', 'See the clinical briefing on a patient overview (last visit, vitals, medicines, labs, alerts)'),
    (gen_random_uuid(), 'CLINIC_ALLERGY_READ', 'View allergies'),
    (gen_random_uuid(), 'CLINIC_ALLERGY_WRITE', 'Record and change allergies'),
    (gen_random_uuid(), 'CLINIC_CONDITION_READ', 'View conditions'),
    (gen_random_uuid(), 'CLINIC_CONDITION_WRITE', 'Record and change conditions'),
    (gen_random_uuid(), 'CLINIC_MEDICATION_READ', 'View the patient''s current medicines'),
    (gen_random_uuid(), 'CLINIC_MEDICATION_WRITE', 'Record and change the patient''s current medicines'),
    (gen_random_uuid(), 'CLINIC_CLINICAL_HISTORY_READ', 'View clinical history'),
    (gen_random_uuid(), 'CLINIC_CLINICAL_HISTORY_WRITE', 'Record clinical history'),
    (gen_random_uuid(), 'CLINIC_VITALS_READ', 'View vital signs and measurements'),
    (gen_random_uuid(), 'CLINIC_VITALS_WRITE', 'Record vital signs and measurements'),
    (gen_random_uuid(), 'CLINIC_VITALS_VOID', 'Void a recorded measurement'),
    (gen_random_uuid(), 'CLINIC_CLINICAL_MATRIX_READ', 'View the clinical matrix'),
    (gen_random_uuid(), 'CLINIC_CLINICAL_MATRIX_WRITE', 'Update the clinical matrix'),
    (gen_random_uuid(), 'CLINIC_NOTE_READ', 'Read patient notes'),
    (gen_random_uuid(), 'CLINIC_NOTE_CREATE', 'Add a patient note'),
    (gen_random_uuid(), 'CLINIC_NOTE_UPDATE', 'Resolve or edit a patient note'),
    (gen_random_uuid(), 'CLINIC_NOTE_LOCK', 'Lock a note against further change'),
    (gen_random_uuid(), 'CLINIC_ADMIN_NOTE_READ', 'Read administrative notes'),
    (gen_random_uuid(), 'CLINIC_PRIVATE_NOTE_READ', 'Read a clinician''s private notes'),
    (gen_random_uuid(), 'CLINIC_CONSULTATION_READ', 'View consultations, drafts, edit history and summaries'),
    (gen_random_uuid(), 'CLINIC_CONSULTATION_CREATE', 'Start a consultation or draft'),
    (gen_random_uuid(), 'CLINIC_CONSULTATION_UPDATE', 'Edit or abandon an unsigned consultation'),
    (gen_random_uuid(), 'CLINIC_CONSULTATION_SIGN', 'Sign a consultation'),
    (gen_random_uuid(), 'CLINIC_CONSULTATION_LOCK', 'Lock a signed consultation'),
    (gen_random_uuid(), 'CLINIC_CONSULTATION_AMEND', 'Add an addendum to a signed consultation'),
    (gen_random_uuid(), 'CLINIC_CONSULTATION_OVERRIDE_REQUIRED_STEP', 'Sign with a required stage overridden (typed reason, audited)'),
    (gen_random_uuid(), 'CLINIC_NURSE_INTAKE_CREATE', 'Start nurse intake on a consultation'),
    (gen_random_uuid(), 'CLINIC_NURSE_INTAKE_UPDATE', 'Resume or edit nurse intake'),
    (gen_random_uuid(), 'CLINIC_NURSE_HANDOFF', 'Send a consultation to the doctor'),
    (gen_random_uuid(), 'CLINIC_NURSE_HANDOFF_ACCEPT', 'Accept a handoff as the doctor'),
    (gen_random_uuid(), 'CLINIC_NURSE_HANDOFF_RETURN', 'Return a handoff to the nurse'),
    (gen_random_uuid(), 'CLINIC_NURSE_HANDOFF_COMPLETE', 'Complete the doctor''s review of a handoff'),
    (gen_random_uuid(), 'CLINIC_PRESCRIPTION_READ', 'View prescriptions and fills'),
    (gen_random_uuid(), 'CLINIC_PRESCRIPTION_CREATE', 'Write a prescription (includes the allergy check)'),
    (gen_random_uuid(), 'CLINIC_PRESCRIPTION_UPDATE', 'Change a draft prescription'),
    (gen_random_uuid(), 'CLINIC_PRESCRIPTION_SIGN', 'Sign a prescription'),
    (gen_random_uuid(), 'CLINIC_PRESCRIPTION_VOID', 'Void a prescription'),
    (gen_random_uuid(), 'CLINIC_PRESCRIPTION_DISPENSE', 'Record a dispense / fill'),
    (gen_random_uuid(), 'CLINIC_SICK_NOTE_READ', 'View sick notes'),
    (gen_random_uuid(), 'CLINIC_SICK_NOTE_CREATE', 'Create a sick note draft'),
    (gen_random_uuid(), 'CLINIC_SICK_NOTE_UPDATE_DRAFT', 'Edit a draft sick note'),
    (gen_random_uuid(), 'CLINIC_SICK_NOTE_SIGN', 'Issue (sign) a medical certificate'),
    (gen_random_uuid(), 'CLINIC_SICK_NOTE_VOID', 'Void a sick note'),
    (gen_random_uuid(), 'CLINIC_SICK_NOTE_DOWNLOAD', 'Download a sick note'),
    (gen_random_uuid(), 'CLINIC_SICK_NOTE_PRINT', 'Print a sick note'),
    (gen_random_uuid(), 'CLINIC_REFERRAL_READ', 'View referrals'),
    (gen_random_uuid(), 'CLINIC_REFERRAL_CREATE', 'Create a referral draft'),
    (gen_random_uuid(), 'CLINIC_REFERRAL_UPDATE', 'Edit a draft referral'),
    (gen_random_uuid(), 'CLINIC_REFERRAL_SIGN', 'Issue (sign) a referral letter'),
    (gen_random_uuid(), 'CLINIC_REFERRAL_VOID', 'Void a referral'),
    (gen_random_uuid(), 'CLINIC_REFERRAL_SEND', 'Send a referral (separate from signing)'),
    (gen_random_uuid(), 'CLINIC_GROWTH_READ', 'View growth measurements and charts'),
    (gen_random_uuid(), 'CLINIC_GROWTH_RECORD', 'Record a growth measurement'),
    (gen_random_uuid(), 'CLINIC_GROWTH_UPDATE', 'Correct a growth measurement'),
    (gen_random_uuid(), 'CLINIC_GROWTH_INTERPRET', 'Record a clinical interpretation of growth'),
    (gen_random_uuid(), 'CLINIC_GROWTH_EXPORT', 'Export or print a growth chart'),
    (gen_random_uuid(), 'CLINIC_RESULT_READ', 'View lab results and critical flags'),
    (gen_random_uuid(), 'CLINIC_RESULT_CREATE', 'Upload a lab result'),
    (gen_random_uuid(), 'CLINIC_RESULT_UPDATE', 'Correct result markers'),
    (gen_random_uuid(), 'CLINIC_RESULT_MATCH', 'Match a result to a patient'),
    (gen_random_uuid(), 'CLINIC_RESULT_INTERPRET', 'Interpret a result (including AI assistance)'),
    (gen_random_uuid(), 'CLINIC_RESULT_REVIEW', 'Mark a result reviewed'),
    (gen_random_uuid(), 'CLINIC_RESULT_FILE', 'File a result to the patient record'),
    (gen_random_uuid(), 'CLINIC_RESULT_ACKNOWLEDGE', 'Acknowledge a result in the results inbox'),
    (gen_random_uuid(), 'CLINIC_DOCUMENT_READ', 'View a document list'),
    (gen_random_uuid(), 'CLINIC_DOCUMENT_CREATE', 'Create a document'),
    (gen_random_uuid(), 'CLINIC_DOCUMENT_DOWNLOAD', 'Download a document'),
    (gen_random_uuid(), 'CLINIC_DOCUMENT_PRINT', 'Print a document'),
    (gen_random_uuid(), 'CLINIC_DOCUMENT_EMAIL', 'Email a document to a patient (delivery is separate from signing)'),
    (gen_random_uuid(), 'CLINIC_DOCUMENT_VOID', 'Void a document'),
    (gen_random_uuid(), 'CLINIC_CONSENT_READ', 'View consent status'),
    (gen_random_uuid(), 'CLINIC_CONSENT_HISTORY_READ', 'View consent history'),
    (gen_random_uuid(), 'CLINIC_CONSENT_RECORD', 'Record consent'),
    (gen_random_uuid(), 'CLINIC_CONSENT_UPDATE', 'Change a consent'),
    (gen_random_uuid(), 'CLINIC_CONSENT_REVOKE', 'Revoke a consent'),
    (gen_random_uuid(), 'CLINIC_RESTRICTED_RECORD_MANAGE', 'Flag a record or document as restricted'),
    (gen_random_uuid(), 'CLINIC_RESTRICTED_RECORD_REQUEST', 'Ask for access to a restricted record'),
    (gen_random_uuid(), 'CLINIC_RESTRICTED_RECORD_ACCESS', 'Open a restricted record once access is granted'),
    (gen_random_uuid(), 'CLINIC_BREAK_GLASS_VIEW', 'Break the glass to view a restricted record (reason required, audited, alerts the practice manager)'),
    (gen_random_uuid(), 'CLINIC_BREAK_GLASS_PRINT', 'Print a restricted record opened by break-glass'),
    (gen_random_uuid(), 'CLINIC_BREAK_GLASS_EXPORT', 'Export a restricted record opened by break-glass'),
    (gen_random_uuid(), 'CLINIC_QUEUE_READ', 'View the handoff queue and today''s queue'),
    (gen_random_uuid(), 'CLINIC_APPOINTMENT_READ', 'View appointments, rooms and the waitlist'),
    (gen_random_uuid(), 'CLINIC_APPOINTMENT_CREATE', 'Book an appointment or add to the waitlist'),
    (gen_random_uuid(), 'CLINIC_APPOINTMENT_UPDATE', 'Confirm, start, complete, no-show or cancel an appointment; send reminders; work the waitlist'),
    (gen_random_uuid(), 'CLINIC_APPOINTMENT_CANCEL', 'Cancel an appointment (split from update when the action endpoint is split)'),
    (gen_random_uuid(), 'CLINIC_APPOINTMENT_RESCHEDULE', 'Reschedule an appointment'),
    (gen_random_uuid(), 'CLINIC_APPOINTMENT_CHECK_IN', 'Check a patient in (split from update when the action endpoint is split)'),
    (gen_random_uuid(), 'CLINIC_QUEUE_MANAGE', 'Manage today''s queue'),
    (gen_random_uuid(), 'CLINIC_PRACTITIONER_READ', 'View practitioners'),
    (gen_random_uuid(), 'CLINIC_PRACTITIONER_MANAGE', 'Register a practitioner'),
    (gen_random_uuid(), 'CLINIC_WORKING_HOURS_WRITE', 'Set a practitioner''s working hours'),
    (gen_random_uuid(), 'CLINIC_TIME_OFF_WRITE', 'Add or cancel practitioner time off'),
    (gen_random_uuid(), 'CLINIC_CLOSURE_MANAGE', 'Create and cancel practice closures'),
    (gen_random_uuid(), 'CLINIC_ROOM_MANAGE', 'Create and edit rooms'),
    (gen_random_uuid(), 'CLINIC_TELEHEALTH_ROOM_CREATE', 'Create a video room for an appointment'),
    (gen_random_uuid(), 'CLINIC_RECALL_READ', 'View the recall worklist'),
    (gen_random_uuid(), 'CLINIC_RECALL_MANAGE', 'Log a recall action (call, snooze, dismiss)'),
    (gen_random_uuid(), 'CLINIC_DASHBOARD_READ', 'View the clinic dashboard'),
    (gen_random_uuid(), 'CLINIC_TIMELINE_READ', 'View a patient timeline'),
    (gen_random_uuid(), 'CLINIC_CATALOGUE_READ', 'Search the medicine and procedure catalogues'),
    (gen_random_uuid(), 'CLINIC_QUESTIONNAIRE_READ', 'Open questionnaires and visit-type settings used in a consultation'),
    (gen_random_uuid(), 'CLINIC_QUESTIONNAIRE_ANSWER', 'Save questionnaire answers on a consultation'),
    (gen_random_uuid(), 'CLINIC_BILL_READ', 'View bills, statements, outstanding balances and revenue'),
    (gen_random_uuid(), 'CLINIC_BILL_CREATE', 'Create a bill'),
    (gen_random_uuid(), 'CLINIC_BILL_ADJUST', 'Adjust a bill (credit, discount); never granted automatically'),
    (gen_random_uuid(), 'CLINIC_PAYMENT_READ', 'View payments'),
    (gen_random_uuid(), 'CLINIC_PAYMENT_CREATE', 'Record a payment'),
    (gen_random_uuid(), 'CLINIC_PAYMENT_ALLOCATE', 'Allocate a scheme payment across claims, including manual override (CLINIC-DEC-006)'),
    (gen_random_uuid(), 'CLINIC_PAYMENT_REVERSE', 'Reverse a payment'),
    (gen_random_uuid(), 'CLINIC_WRITE_OFF', 'Write off a shortfall as a controlled transaction (CLINIC-DEC-001)'),
    (gen_random_uuid(), 'CLINIC_CLAIM_READ', 'View claims and claim documents'),
    (gen_random_uuid(), 'CLINIC_CLAIM_CREATE', 'Create a claim from a consultation'),
    (gen_random_uuid(), 'CLINIC_CLAIM_SUBMIT', 'Submit claims'),
    (gen_random_uuid(), 'CLINIC_CLAIM_PROGRESS', 'Move a claim through accept, reject, pay (to be split by the claims-money work)'),
    (gen_random_uuid(), 'CLINIC_CLAIM_CORRECT', 'Correct a submitted claim through the correction workflow (CLINIC-DEC-004)'),
    (gen_random_uuid(), 'CLINIC_CLAIM_REVERSE', 'Reverse or credit a claim (CLINIC-DEC-002, 003)'),
    (gen_random_uuid(), 'CLINIC_CLAIM_RESUBMIT', 'Resubmit a corrected claim'),
    (gen_random_uuid(), 'CLINIC_ACCESS_LOG_READ', 'View the clinic access log')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT DISTINCT rp.role_id, np.id
FROM role_permissions rp
JOIN permissions op ON op.id = rp.permission_id
JOIN (VALUES
    ('CLINIC_READ','CLINIC_PATIENT_ACCESS'),
    ('CLINIC_READ','CLINIC_PATIENT_READ'),
    ('CLINIC_WRITE','CLINIC_PATIENT_CREATE'),
    ('CLINIC_WRITE','CLINIC_PATIENT_UPDATE'),
    ('CLINIC_ADMIN','CLINIC_PATIENT_ARCHIVE'),
    ('CLINIC_ADMIN','CLINIC_PATIENT_MERGE'),
    ('CLINIC_WRITE','CLINIC_PATIENT_DUPLICATE_REVIEW'),
    ('CLINIC_READ','CLINIC_PATIENT_DEMOGRAPHICS_READ'),
    ('CLINIC_WRITE','CLINIC_PATIENT_DEMOGRAPHICS_WRITE'),
    ('CLINIC_READ','CLINIC_PATIENT_CONTACT_READ'),
    ('CLINIC_WRITE','CLINIC_PATIENT_CONTACT_WRITE'),
    ('CLINIC_READ','CLINIC_PATIENT_ADDRESS_READ'),
    ('CLINIC_WRITE','CLINIC_PATIENT_ADDRESS_WRITE'),
    ('CLINIC_READ','CLINIC_PATIENT_RELATIONSHIP_READ'),
    ('CLINIC_WRITE','CLINIC_PATIENT_RELATIONSHIP_WRITE'),
    ('CLINIC_READ','CLINIC_PATIENT_EMERGENCY_CONTACT_READ'),
    ('CLINIC_WRITE','CLINIC_PATIENT_EMERGENCY_CONTACT_WRITE'),
    ('CLINIC_READ','CLINIC_CLINICAL_SUMMARY_READ'),
    ('CLINIC_READ','CLINIC_ALLERGY_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_ALLERGY_WRITE'),
    ('CLINIC_READ','CLINIC_CONDITION_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_CONDITION_WRITE'),
    ('CLINIC_READ','CLINIC_MEDICATION_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_MEDICATION_WRITE'),
    ('CLINIC_READ','CLINIC_CLINICAL_HISTORY_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_CLINICAL_HISTORY_WRITE'),
    ('CLINIC_READ','CLINIC_VITALS_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_VITALS_WRITE'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_VITALS_VOID'),
    ('CLINIC_READ','CLINIC_CLINICAL_MATRIX_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_CLINICAL_MATRIX_WRITE'),
    ('CLINIC_READ','CLINIC_NOTE_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_NOTE_CREATE'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_NOTE_UPDATE'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_NOTE_LOCK'),
    ('CLINIC_READ','CLINIC_ADMIN_NOTE_READ'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_PRIVATE_NOTE_READ'),
    ('CLINIC_READ','CLINIC_CONSULTATION_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_CONSULTATION_CREATE'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_CONSULTATION_UPDATE'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_CONSULTATION_SIGN'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_CONSULTATION_LOCK'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_CONSULTATION_AMEND'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_CONSULTATION_OVERRIDE_REQUIRED_STEP'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_NURSE_INTAKE_CREATE'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_NURSE_INTAKE_UPDATE'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_NURSE_HANDOFF'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_NURSE_HANDOFF_ACCEPT'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_NURSE_HANDOFF_RETURN'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_NURSE_HANDOFF_COMPLETE'),
    ('CLINIC_READ','CLINIC_PRESCRIPTION_READ'),
    ('CLINIC_PRESCRIPTION_WRITE','CLINIC_PRESCRIPTION_CREATE'),
    ('CLINIC_PRESCRIPTION_WRITE','CLINIC_PRESCRIPTION_UPDATE'),
    ('CLINIC_PRESCRIPTION_WRITE','CLINIC_PRESCRIPTION_SIGN'),
    ('CLINIC_PRESCRIPTION_WRITE','CLINIC_PRESCRIPTION_VOID'),
    ('CLINIC_PRESCRIPTION_WRITE','CLINIC_PRESCRIPTION_DISPENSE'),
    ('CLINIC_READ','CLINIC_SICK_NOTE_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_SICK_NOTE_CREATE'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_SICK_NOTE_UPDATE_DRAFT'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_SICK_NOTE_SIGN'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_SICK_NOTE_VOID'),
    ('CLINIC_READ','CLINIC_SICK_NOTE_DOWNLOAD'),
    ('CLINIC_READ','CLINIC_SICK_NOTE_PRINT'),
    ('CLINIC_READ','CLINIC_REFERRAL_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_REFERRAL_CREATE'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_REFERRAL_UPDATE'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_REFERRAL_SIGN'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_REFERRAL_VOID'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_REFERRAL_SEND'),
    ('CLINIC_READ','CLINIC_GROWTH_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_GROWTH_RECORD'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_GROWTH_UPDATE'),
    ('CLINIC_CLINICAL_SIGN','CLINIC_GROWTH_INTERPRET'),
    ('CLINIC_READ','CLINIC_GROWTH_EXPORT'),
    ('CLINIC_READ','CLINIC_RESULT_READ'),
    ('CLINIC_LAB_WRITE','CLINIC_RESULT_CREATE'),
    ('CLINIC_LAB_WRITE','CLINIC_RESULT_UPDATE'),
    ('CLINIC_LAB_WRITE','CLINIC_RESULT_MATCH'),
    ('CLINIC_LAB_WRITE','CLINIC_RESULT_INTERPRET'),
    ('CLINIC_LAB_WRITE','CLINIC_RESULT_REVIEW'),
    ('CLINIC_LAB_WRITE','CLINIC_RESULT_FILE'),
    ('CLINIC_LAB_WRITE','CLINIC_RESULT_ACKNOWLEDGE'),
    ('CLINIC_READ','CLINIC_DOCUMENT_READ'),
    ('CLINIC_WRITE','CLINIC_DOCUMENT_CREATE'),
    ('CLINIC_READ','CLINIC_DOCUMENT_DOWNLOAD'),
    ('CLINIC_READ','CLINIC_DOCUMENT_PRINT'),
    ('CLINIC_BILLING_WRITE','CLINIC_DOCUMENT_EMAIL'),
    ('CLINIC_ADMIN','CLINIC_DOCUMENT_VOID'),
    ('CLINIC_READ','CLINIC_CONSENT_READ'),
    ('CLINIC_READ','CLINIC_CONSENT_HISTORY_READ'),
    ('CLINIC_WRITE','CLINIC_CONSENT_RECORD'),
    ('CLINIC_WRITE','CLINIC_CONSENT_UPDATE'),
    ('CLINIC_WRITE','CLINIC_CONSENT_REVOKE'),
    ('CLINIC_READ','CLINIC_QUEUE_READ'),
    ('CLINIC_READ','CLINIC_APPOINTMENT_READ'),
    ('CLINIC_WRITE','CLINIC_APPOINTMENT_CREATE'),
    ('CLINIC_WRITE','CLINIC_APPOINTMENT_UPDATE'),
    ('CLINIC_WRITE','CLINIC_APPOINTMENT_CANCEL'),
    ('CLINIC_WRITE','CLINIC_APPOINTMENT_RESCHEDULE'),
    ('CLINIC_WRITE','CLINIC_APPOINTMENT_CHECK_IN'),
    ('CLINIC_WRITE','CLINIC_QUEUE_MANAGE'),
    ('CLINIC_READ','CLINIC_PRACTITIONER_READ'),
    ('CLINIC_WRITE','CLINIC_PRACTITIONER_MANAGE'),
    ('CLINIC_WRITE','CLINIC_WORKING_HOURS_WRITE'),
    ('CLINIC_WRITE','CLINIC_TIME_OFF_WRITE'),
    ('CLINIC_ADMIN','CLINIC_CLOSURE_MANAGE'),
    ('CLINIC_ADMIN','CLINIC_ROOM_MANAGE'),
    ('CLINIC_READ','CLINIC_TELEHEALTH_ROOM_CREATE'),
    ('CLINIC_READ','CLINIC_RECALL_READ'),
    ('CLINIC_WRITE','CLINIC_RECALL_MANAGE'),
    ('CLINIC_READ','CLINIC_DASHBOARD_READ'),
    ('CLINIC_READ','CLINIC_TIMELINE_READ'),
    ('CLINIC_READ','CLINIC_CATALOGUE_READ'),
    ('CLINIC_READ','CLINIC_QUESTIONNAIRE_READ'),
    ('CLINIC_CLINICAL_WRITE','CLINIC_QUESTIONNAIRE_ANSWER'),
    ('CLINIC_BILLING_READ','CLINIC_BILL_READ'),
    ('CLINIC_BILLING_WRITE','CLINIC_BILL_CREATE'),
    ('CLINIC_BILLING_READ','CLINIC_PAYMENT_READ'),
    ('CLINIC_BILLING_WRITE','CLINIC_PAYMENT_CREATE'),
    ('CLINIC_BILLING_READ','CLINIC_CLAIM_READ'),
    ('CLINIC_BILLING_WRITE','CLINIC_CLAIM_CREATE'),
    ('CLINIC_BILLING_WRITE','CLINIC_CLAIM_SUBMIT'),
    ('CLINIC_BILLING_WRITE','CLINIC_CLAIM_PROGRESS'),
    ('CLINIC_ADMIN','CLINIC_ACCESS_LOG_READ')
) AS m(legacy, fine) ON m.legacy = op.name
JOIN permissions np ON np.name = m.fine
ON CONFLICT DO NOTHING;
