ALTER TABLE security_incidents
    ADD COLUMN IF NOT EXISTS status       VARCHAR(50)  NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS severity     VARCHAR(50)  NOT NULL DEFAULT 'MEDIUM',
    ADD COLUMN IF NOT EXISTS title        VARCHAR(255),
    ADD COLUMN IF NOT EXISTS description  TEXT,
    ADD COLUMN IF NOT EXISTS guard_id     UUID,
    ADD COLUMN IF NOT EXISTS shift_id     UUID,
    ADD COLUMN IF NOT EXISTS latitude     DECIMAL(10, 7),
    ADD COLUMN IF NOT EXISTS longitude    DECIMAL(10, 7),
    ADD COLUMN IF NOT EXISTS acknowledged_at  TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS resolved_at      TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW();