// security/application/internal/SecurityPdfBrandingHelper.java

package za.co.handyflow.platform.security.application.internal;

import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import za.co.handyflow.platform.identity.TenantDetails;
import za.co.handyflow.platform.identity.TenantFacade;
import za.co.handyflow.platform.shared.ResourceNotFoundException;
import za.co.handyflow.platform.shared.TenantId;

import java.net.URL;

/**
 * SecurityPdfBrandingHelper — shared tenant-logo header/footer for every PDF
 * service in this module.
 *
 * WHY extracted now, and not when PdfReportService first added logo support?
 * At two call sites (Quote/Invoice in a different module, PdfReportService
 * in this one) copy-paste matched the codebase's existing convention. A
 * third and fourth PDF service in the SAME module needing the identical
 * logic is the point where duplication stops being a reasonable shortcut —
 * see the conversation history for that reasoning. PdfReportService itself
 * is NOT refactored to use this (it already works; no reason to touch a
 * working file just to deduplicate) — but every new PDF service from here
 * on should use this instead of copying decodeLogoBytes() a fifth time.
 *
 * CRITICAL — same data-URI caveat as PdfReportService/QuotePdfService:
 * TenantService.uploadLogo() stores logoUrl as "data:<mime>;base64,<data>",
 * not a real HTTP(S) URL. decodeLogoBytes() below handles that first.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class SecurityPdfBrandingHelper {

    private final TenantFacade tenantFacade;

    public TenantDetails resolveTenant(TenantId tenantId) {
        return tenantFacade.findTenantDetails(tenantId)
                .orElseThrow(() -> new ResourceNotFoundException("Tenant", tenantId.getValue().toString()));
    }

    /**
     * Adds a branded header bar: logo (if available) + company name, report
     * title, subject line, and a right-aligned reference (period, date,
     * or reference number — whatever fits the calling report).
     */
    public void addBrandedHeader(Document doc, String title, String subject, String reference,
                                 TenantDetails tenant, DeviceRgb brandColor) {
        Table header = new Table(UnitValue.createPercentArray(new float[]{3, 1}))
                .useAllAvailableWidth()
                .setBackgroundColor(brandColor)
                .setMarginBottom(16);

        Cell titleCell = new Cell(1, 1)
                .setBorder(Border.NO_BORDER)
                .setPadding(12);

        Image logo = tryLoadLogoImage(tenant);
        if (logo != null) {
            Table logoCard = new Table(new float[]{1})
                    .setWidth(UnitValue.createPointValue(90))
                    .setBackgroundColor(ColorConstants.WHITE);
            logoCard.addCell(new Cell().setBorder(Border.NO_BORDER).setPadding(4).add(logo));
            titleCell.add(logoCard);
        }

        String companyName = (tenant != null && tenant.companyName() != null)
                ? tenant.companyName() : "HandyFlow Security";

        titleCell.add(new Paragraph(companyName).setFontSize(8)
                .setFontColor(ColorConstants.WHITE).setMarginTop(logo != null ? 6 : 0));
        titleCell.add(new Paragraph(title).setFontSize(16).setBold()
                .setFontColor(ColorConstants.WHITE));
        if (subject != null && !subject.isBlank()) {
            titleCell.add(new Paragraph(subject).setFontSize(11)
                    .setFontColor(ColorConstants.WHITE));
        }

        Cell refCell = new Cell(1, 1)
                .add(new Paragraph(reference != null ? reference : "")
                        .setFontSize(12).setBold()
                        .setFontColor(ColorConstants.WHITE)
                        .setTextAlignment(TextAlignment.RIGHT))
                .setBorder(Border.NO_BORDER)
                .setPadding(12);

        header.addCell(titleCell);
        header.addCell(refCell);
        doc.add(header);
    }

    public void addBrandedFooter(Document doc, TenantDetails tenant) {
        String companyName = (tenant != null && tenant.companyName() != null)
                ? tenant.companyName() : "HandyFlow Security";
        doc.add(new Paragraph(
                "Generated by " + companyName + " via HandyFlow Security Platform — " +
                        java.time.ZonedDateTime.now(java.time.ZoneOffset.UTC)
                                .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'")))
                .setFontSize(7)
                .setFontColor(new DeviceRgb(120, 120, 120))
                .setTextAlignment(TextAlignment.RIGHT)
                .setMarginTop(20));
    }

    // ── Logo loading (identical logic to PdfReportService's private copy) ────

    private Image tryLoadLogoImage(TenantDetails tenant) {
        if (tenant == null || tenant.logoUrl() == null || tenant.logoUrl().isBlank()) {
            return null;
        }
        try {
            byte[] imageBytes = decodeLogoBytes(tenant.logoUrl());
            return new Image(ImageDataFactory.create(imageBytes))
                    .setMaxHeight(36).setAutoScale(false);
        } catch (Exception ex) {
            log.warn("[Reporting] Could not load tenant logo tenant={}: {}",
                    tenant.slug(), ex.getMessage());
            return null;
        }
    }

    private byte[] decodeLogoBytes(String logoUrl) throws Exception {
        if (logoUrl.startsWith("data:")) {
            int commaIdx = logoUrl.indexOf(',');
            if (commaIdx < 0) {
                throw new IllegalArgumentException("Malformed data URI — no comma separator found");
            }
            String base64Payload = logoUrl.substring(commaIdx + 1);
            return java.util.Base64.getDecoder().decode(base64Payload);
        }
        try (var in = new URL(logoUrl).openStream()) {
            return in.readAllBytes();
        }
    }
}