// ScPurchaseOrderRepository.java
package za.co.handyflow.platform.supplychain.domain.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import za.co.handyflow.platform.supplychain.domain.enums.PoStatus;
import za.co.handyflow.platform.supplychain.domain.model.ScPurchaseOrder;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

public interface ScPurchaseOrderRepository extends JpaRepository<ScPurchaseOrder, UUID> {

    @Query("SELECT p FROM ScPurchaseOrder p WHERE p.tenantId = :tenantId ORDER BY p.createdAt DESC")
    Page<ScPurchaseOrder> findByTenantId(@Param("tenantId") UUID tenantId, Pageable pageable);

    @Query("SELECT p FROM ScPurchaseOrder p WHERE p.tenantId = :tenantId AND p.status = :status ORDER BY p.createdAt DESC")
    Page<ScPurchaseOrder> findByTenantIdAndStatus(@Param("tenantId") UUID tenantId,
                                                  @Param("status") PoStatus status,
                                                  Pageable pageable);

    @Query("SELECT p FROM ScPurchaseOrder p WHERE p.tenantId = :tenantId AND p.id = :id")
    Optional<ScPurchaseOrder> findByTenantIdAndId(@Param("tenantId") UUID tenantId, @Param("id") UUID id);

    @Query("SELECT COUNT(p) FROM ScPurchaseOrder p WHERE p.tenantId = :tenantId AND p.status IN :statuses")
    long countByTenantIdAndStatusIn(@Param("tenantId") UUID tenantId, @Param("statuses") List<PoStatus> statuses);

    /**
     * Removed the fragile MAX(CAST(SUBSTRING(...))) sequence query.
     * PO numbers are now generated by SequenceService.next(tenantId, "PO")
     * which uses an atomic PostgreSQL upsert on the pm_counters table.
     * This method is intentionally absent — callers use SequenceService directly.
     */
}