package za.co.handyflow.platform.ap.domain.model;

import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import za.co.handyflow.platform.shared.TenantId;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

@Entity
@Table(name = "ap_recurring_bill_templates")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class ApRecurringBillTemplate {

    @Id
    private UUID id = UUID.randomUUID();

    @Embedded
    @AttributeOverride(name = "value", column = @Column(name = "tenant_id", nullable = false))
    private TenantId tenantId;

    @Column(name = "supplier_id") private UUID supplierId;
    @Column(name = "supplier_name", nullable = false) private String supplierName;
    @Column(nullable = false) private String category = "OTHER";
    @Column(nullable = false) private String description;

    @Column(nullable = false, precision = 15, scale = 2) private BigDecimal amount;
    @Column(name = "vat_amount", nullable = false, precision = 15, scale = 2) private BigDecimal vatAmount = BigDecimal.ZERO;

    // Only MONTHLY is actually generated by anything right now — the
    // column exists so a future WEEKLY/QUARTERLY frequency doesn't need
    // a schema change, but ApRecurringBillService only implements the
    // monthly advance-by-one-month logic today.
    @Column(nullable = false) private String frequency = "MONTHLY";

    // Capped at 28 in the factory below — not 29/30/31 — so this stays
    // valid every month including February, with no special-casing
    // needed anywhere else in the generation logic.
    @Column(name = "day_of_month", nullable = false) private int dayOfMonth;

    // How many days BEFORE the due date the draft bill actually gets
    // created — matches the same "reminder window" concept
    // ApBillDueSoonScheduler already uses elsewhere in this module,
    // default kept the same (7) for consistency, not because they're
    // technically related.
    @Column(name = "lead_days", nullable = false) private int leadDays = 7;

    @Column(name = "next_due_date", nullable = false) private LocalDate nextDueDate;
    @Column(name = "last_generated_bill_id") private UUID lastGeneratedBillId;
    @Column(name = "last_generated_at") private Instant lastGeneratedAt;

    @Column(nullable = false) private boolean active = true;
    private String notes;

    @Column(name = "created_by") private UUID createdBy;
    @Column(name = "created_at") private Instant createdAt;
    @Column(name = "updated_at") private Instant updatedAt;
    @Column(name = "deleted_at") private Instant deletedAt;

    @Version private Long version;

    public static ApRecurringBillTemplate create(TenantId tenantId, UUID supplierId, String supplierName,
                                                 String category, String description,
                                                 BigDecimal amount, BigDecimal vatAmount,
                                                 int dayOfMonth, Integer leadDays,
                                                 String notes, UUID createdBy) {
        if (dayOfMonth < 1 || dayOfMonth > 28)
            throw new IllegalArgumentException(
                    "Day of month must be between 1 and 28 — capped there so it stays valid every month, including February");

        ApRecurringBillTemplate t = new ApRecurringBillTemplate();
        t.tenantId     = tenantId;
        t.supplierId   = supplierId;
        t.supplierName = supplierName;
        t.category     = category != null ? category : "OTHER";
        t.description  = description;
        t.amount       = amount;
        t.vatAmount    = vatAmount != null ? vatAmount : BigDecimal.ZERO;
        t.dayOfMonth   = dayOfMonth;
        t.leadDays     = leadDays != null ? leadDays : 7;
        t.frequency    = "MONTHLY";
        t.active       = true;
        t.notes        = notes;
        t.createdBy    = createdBy;
        t.nextDueDate  = computeInitialDueDate(LocalDate.now(), dayOfMonth);
        t.createdAt    = Instant.now();
        t.updatedAt    = Instant.now();
        return t;
    }

    // If today's already past this month's day-of-month, the first due
    // date is next month — a template created on the 20th for "due on
    // the 5th" shouldn't immediately generate a bill for a date that's
    // already gone.
    private static LocalDate computeInitialDueDate(LocalDate from, int dayOfMonth) {
        LocalDate candidate = from.withDayOfMonth(dayOfMonth);
        if (!candidate.isAfter(from)) candidate = candidate.plusMonths(1);
        return candidate;
    }

    public void advanceToNextDue(UUID generatedBillId) {
        this.nextDueDate         = nextDueDate.plusMonths(1);
        this.lastGeneratedBillId = generatedBillId;
        this.lastGeneratedAt     = Instant.now();
        this.updatedAt           = Instant.now();
    }

    public void pause()  { this.active = false; this.updatedAt = Instant.now(); }
    public void resume() { this.active = true;  this.updatedAt = Instant.now(); }

    public void update(String description, BigDecimal amount, BigDecimal vatAmount,
                       int dayOfMonth, Integer leadDays, String notes) {
        if (dayOfMonth < 1 || dayOfMonth > 28)
            throw new IllegalArgumentException("Day of month must be between 1 and 28");
        this.description = description;
        this.amount       = amount;
        this.vatAmount    = vatAmount != null ? vatAmount : BigDecimal.ZERO;
        this.dayOfMonth   = dayOfMonth;
        this.leadDays     = leadDays != null ? leadDays : this.leadDays;
        this.notes        = notes;
        this.updatedAt    = Instant.now();
    }
}