package za.co.handyflow.platform.clinic.application.internal;

import java.util.Arrays;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * The Clinic permission catalogue: what a user can be allowed to do, one permission per capability (not one per module).
 * <ul>
 *   <li><code>legacy</code> is the coarse permission whose holders received this one automatically in V363, so nobody lost
 *       access when endpoints moved from the coarse permissions to these. <code>null</code> means nobody gets it
 *       automatically (break-glass and the money actions that need a deliberate grant).</li>
 *   <li><code>enforced</code> is true when at least one endpoint requires it today; the rest are reserved names so roles can
 *       be designed now and the endpoints can follow without another permission migration.</li>
 * </ul>
 * Pure: no Spring, no database. See CLINIC-ACCESS-MATRIX.md for the role matrix and the endpoint authorization matrix.
 */
public enum ClinicPermission {

    CLINIC_PATIENT_ACCESS(Group.PATIENT, Kind.READ, "CLINIC_READ", false,
            "Open a patient's record (context rules such as care relationship and restricted records apply)"),
    CLINIC_PATIENT_READ(Group.PATIENT, Kind.READ, "CLINIC_READ", true,
            "Search and view patients"),
    CLINIC_PATIENT_CREATE(Group.PATIENT, Kind.WRITE, "CLINIC_WRITE", true,
            "Register a patient"),
    CLINIC_PATIENT_UPDATE(Group.PATIENT, Kind.WRITE, "CLINIC_WRITE", true,
            "Edit a patient's registration details"),
    CLINIC_PATIENT_ARCHIVE(Group.PATIENT, Kind.MANAGE, "CLINIC_ADMIN", false,
            "Archive a patient record"),
    CLINIC_PATIENT_MERGE(Group.PATIENT, Kind.MANAGE, "CLINIC_ADMIN", false,
            "Merge duplicate patient records"),
    CLINIC_PATIENT_DUPLICATE_REVIEW(Group.PATIENT, Kind.WRITE, "CLINIC_WRITE", false,
            "Review and resolve possible duplicate patients"),
    CLINIC_PATIENT_DEMOGRAPHICS_READ(Group.PATIENT, Kind.READ, "CLINIC_READ", false,
            "View name, date of birth, sex and ID number"),
    CLINIC_PATIENT_DEMOGRAPHICS_WRITE(Group.PATIENT, Kind.WRITE, "CLINIC_WRITE", false,
            "Change name, date of birth, sex and ID number"),
    CLINIC_PATIENT_CONTACT_READ(Group.PATIENT, Kind.READ, "CLINIC_READ", false,
            "View phone and email"),
    CLINIC_PATIENT_CONTACT_WRITE(Group.PATIENT, Kind.WRITE, "CLINIC_WRITE", false,
            "Change phone and email"),
    CLINIC_PATIENT_ADDRESS_READ(Group.PATIENT, Kind.READ, "CLINIC_READ", false,
            "View addresses"),
    CLINIC_PATIENT_ADDRESS_WRITE(Group.PATIENT, Kind.WRITE, "CLINIC_WRITE", false,
            "Change addresses"),
    CLINIC_PATIENT_RELATIONSHIP_READ(Group.PATIENT, Kind.READ, "CLINIC_READ", true,
            "View family and guarantor relationships"),
    CLINIC_PATIENT_RELATIONSHIP_WRITE(Group.PATIENT, Kind.WRITE, "CLINIC_WRITE", false,
            "Change family and guarantor relationships"),
    CLINIC_PATIENT_EMERGENCY_CONTACT_READ(Group.PATIENT, Kind.READ, "CLINIC_READ", false,
            "View emergency contacts"),
    CLINIC_PATIENT_EMERGENCY_CONTACT_WRITE(Group.PATIENT, Kind.WRITE, "CLINIC_WRITE", false,
            "Change emergency contacts"),
    CLINIC_CLINICAL_SUMMARY_READ(Group.CLINICAL_SUMMARY, Kind.READ, "CLINIC_READ", true,
            "See the clinical briefing on a patient overview (last visit, vitals, medicines, labs, alerts)"),
    CLINIC_ALLERGY_READ(Group.CLINICAL_SUMMARY, Kind.READ, "CLINIC_READ", true,
            "View allergies"),
    CLINIC_ALLERGY_WRITE(Group.CLINICAL_SUMMARY, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Record and change allergies"),
    CLINIC_CONDITION_READ(Group.CLINICAL_SUMMARY, Kind.READ, "CLINIC_READ", true,
            "View conditions"),
    CLINIC_CONDITION_WRITE(Group.CLINICAL_SUMMARY, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Record and change conditions"),
    CLINIC_MEDICATION_READ(Group.CLINICAL_SUMMARY, Kind.READ, "CLINIC_READ", true,
            "View the patient's current medicines"),
    CLINIC_MEDICATION_WRITE(Group.CLINICAL_SUMMARY, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Record and change the patient's current medicines"),
    CLINIC_CLINICAL_HISTORY_READ(Group.CLINICAL_SUMMARY, Kind.READ, "CLINIC_READ", true,
            "View clinical history"),
    CLINIC_CLINICAL_HISTORY_WRITE(Group.CLINICAL_SUMMARY, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Record clinical history"),
    CLINIC_VITALS_READ(Group.CLINICAL_SUMMARY, Kind.READ, "CLINIC_READ", true,
            "View vital signs and measurements"),
    CLINIC_VITALS_WRITE(Group.CLINICAL_SUMMARY, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Record vital signs and measurements"),
    CLINIC_VITALS_VOID(Group.CLINICAL_SUMMARY, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Void a recorded measurement"),
    CLINIC_CLINICAL_MATRIX_READ(Group.CLINICAL_SUMMARY, Kind.READ, "CLINIC_READ", false,
            "View the clinical matrix"),
    CLINIC_CLINICAL_MATRIX_WRITE(Group.CLINICAL_SUMMARY, Kind.WRITE, "CLINIC_CLINICAL_WRITE", false,
            "Update the clinical matrix"),
    CLINIC_NOTE_READ(Group.NOTES, Kind.READ, "CLINIC_READ", true,
            "Read patient notes"),
    CLINIC_NOTE_CREATE(Group.NOTES, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Add a patient note"),
    CLINIC_NOTE_UPDATE(Group.NOTES, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Resolve or edit a patient note"),
    CLINIC_NOTE_LOCK(Group.NOTES, Kind.SIGN, "CLINIC_CLINICAL_WRITE", false,
            "Lock a note against further change"),
    CLINIC_ADMIN_NOTE_READ(Group.NOTES, Kind.READ, "CLINIC_READ", false,
            "Read administrative notes"),
    CLINIC_PRIVATE_NOTE_READ(Group.NOTES, Kind.READ, "CLINIC_CLINICAL_SIGN", false,
            "Read a clinician's private notes"),
    CLINIC_TASK_READ(Group.SCHEDULING, Kind.READ, "CLINIC_READ", true,
            "See clinic tasks (follow-ups, calls, results to chase)"),
    CLINIC_TASK_CREATE(Group.SCHEDULING, Kind.WRITE, "CLINIC_WRITE", true,
            "Create a clinic task for yourself or a colleague"),
    CLINIC_TASK_COMPLETE(Group.SCHEDULING, Kind.WRITE, "CLINIC_WRITE", true,
            "Complete or dismiss a clinic task"),
    CLINIC_CONSULTATION_READ(Group.CONSULTATION, Kind.READ, "CLINIC_READ", true,
            "View consultations, drafts, edit history and summaries"),
    CLINIC_CONSULTATION_CREATE(Group.CONSULTATION, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Start a consultation or draft"),
    CLINIC_CONSULTATION_UPDATE(Group.CONSULTATION, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Edit or abandon an unsigned consultation"),
    CLINIC_CONSULTATION_SIGN(Group.CONSULTATION, Kind.SIGN, "CLINIC_CLINICAL_SIGN", true,
            "Sign a consultation"),
    CLINIC_CONSULTATION_LOCK(Group.CONSULTATION, Kind.SIGN, "CLINIC_CLINICAL_SIGN", false,
            "Lock a signed consultation"),
    CLINIC_CONSULTATION_AMEND(Group.CONSULTATION, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Add an addendum to a signed consultation"),
    CLINIC_CONSULTATION_OVERRIDE_REQUIRED_STEP(Group.CONSULTATION, Kind.SIGN, "CLINIC_CLINICAL_SIGN", false,
            "Sign with a required stage overridden (typed reason, audited)"),
    CLINIC_NURSE_INTAKE_CREATE(Group.NURSE_WORKFLOW, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Start nurse intake on a consultation"),
    CLINIC_NURSE_INTAKE_UPDATE(Group.NURSE_WORKFLOW, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Resume or edit nurse intake"),
    CLINIC_NURSE_HANDOFF(Group.NURSE_WORKFLOW, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Send a consultation to the doctor"),
    CLINIC_NURSE_HANDOFF_ACCEPT(Group.NURSE_WORKFLOW, Kind.SIGN, "CLINIC_CLINICAL_SIGN", true,
            "Accept a handoff as the doctor"),
    CLINIC_NURSE_HANDOFF_RETURN(Group.NURSE_WORKFLOW, Kind.SIGN, "CLINIC_CLINICAL_SIGN", true,
            "Return a handoff to the nurse"),
    CLINIC_NURSE_HANDOFF_COMPLETE(Group.NURSE_WORKFLOW, Kind.SIGN, "CLINIC_CLINICAL_SIGN", true,
            "Complete the doctor's review of a handoff"),
    CLINIC_PRESCRIPTION_READ(Group.PRESCRIPTION, Kind.READ, "CLINIC_READ", true,
            "View prescriptions and fills"),
    CLINIC_PRESCRIPTION_CREATE(Group.PRESCRIPTION, Kind.WRITE, "CLINIC_PRESCRIPTION_WRITE", true,
            "Write a prescription (includes the allergy check)"),
    CLINIC_PRESCRIPTION_UPDATE(Group.PRESCRIPTION, Kind.WRITE, "CLINIC_PRESCRIPTION_WRITE", false,
            "Change a draft prescription"),
    CLINIC_PRESCRIPTION_SIGN(Group.PRESCRIPTION, Kind.SIGN, "CLINIC_PRESCRIPTION_WRITE", false,
            "Sign a prescription"),
    CLINIC_PRESCRIPTION_VOID(Group.PRESCRIPTION, Kind.SIGN, "CLINIC_PRESCRIPTION_WRITE", false,
            "Void a prescription"),
    CLINIC_PRESCRIPTION_DISPENSE(Group.PRESCRIPTION, Kind.WRITE, "CLINIC_PRESCRIPTION_WRITE", true,
            "Record a dispense / fill"),
    CLINIC_SICK_NOTE_READ(Group.SICK_NOTE, Kind.READ, "CLINIC_READ", false,
            "View sick notes"),
    CLINIC_SICK_NOTE_CREATE(Group.SICK_NOTE, Kind.WRITE, "CLINIC_CLINICAL_WRITE", false,
            "Create a sick note draft"),
    CLINIC_SICK_NOTE_UPDATE_DRAFT(Group.SICK_NOTE, Kind.WRITE, "CLINIC_CLINICAL_WRITE", false,
            "Edit a draft sick note"),
    CLINIC_SICK_NOTE_SIGN(Group.SICK_NOTE, Kind.SIGN, "CLINIC_CLINICAL_SIGN", true,
            "Issue (sign) a medical certificate"),
    CLINIC_SICK_NOTE_VOID(Group.SICK_NOTE, Kind.SIGN, "CLINIC_CLINICAL_SIGN", false,
            "Void a sick note"),
    CLINIC_SICK_NOTE_DOWNLOAD(Group.SICK_NOTE, Kind.READ, "CLINIC_READ", false,
            "Download a sick note"),
    CLINIC_SICK_NOTE_PRINT(Group.SICK_NOTE, Kind.READ, "CLINIC_READ", false,
            "Print a sick note"),
    CLINIC_REFERRAL_READ(Group.REFERRAL, Kind.READ, "CLINIC_READ", false,
            "View referrals"),
    CLINIC_REFERRAL_CREATE(Group.REFERRAL, Kind.WRITE, "CLINIC_CLINICAL_WRITE", false,
            "Create a referral draft"),
    CLINIC_REFERRAL_UPDATE(Group.REFERRAL, Kind.WRITE, "CLINIC_CLINICAL_WRITE", false,
            "Edit a draft referral"),
    CLINIC_REFERRAL_SIGN(Group.REFERRAL, Kind.SIGN, "CLINIC_CLINICAL_SIGN", true,
            "Issue (sign) a referral letter"),
    CLINIC_REFERRAL_VOID(Group.REFERRAL, Kind.SIGN, "CLINIC_CLINICAL_SIGN", false,
            "Void a referral"),
    CLINIC_REFERRAL_SEND(Group.REFERRAL, Kind.SEND, "CLINIC_CLINICAL_SIGN", false,
            "Send a referral (separate from signing)"),
    CLINIC_GROWTH_READ(Group.GROWTH, Kind.READ, "CLINIC_READ", true,
            "View growth measurements and charts"),
    CLINIC_GROWTH_RECORD(Group.GROWTH, Kind.WRITE, "CLINIC_CLINICAL_WRITE", false,
            "Record a growth measurement"),
    CLINIC_GROWTH_UPDATE(Group.GROWTH, Kind.WRITE, "CLINIC_CLINICAL_WRITE", false,
            "Correct a growth measurement"),
    CLINIC_GROWTH_INTERPRET(Group.GROWTH, Kind.SIGN, "CLINIC_CLINICAL_SIGN", false,
            "Record a clinical interpretation of growth"),
    CLINIC_GROWTH_EXPORT(Group.GROWTH, Kind.READ, "CLINIC_READ", false,
            "Export or print a growth chart"),
    CLINIC_RESULT_READ(Group.RESULTS, Kind.READ, "CLINIC_READ", true,
            "View lab results and critical flags"),
    CLINIC_RESULT_CREATE(Group.RESULTS, Kind.WRITE, "CLINIC_LAB_WRITE", true,
            "Upload a lab result"),
    CLINIC_RESULT_UPDATE(Group.RESULTS, Kind.WRITE, "CLINIC_LAB_WRITE", true,
            "Correct result markers"),
    CLINIC_RESULT_MATCH(Group.RESULTS, Kind.WRITE, "CLINIC_LAB_WRITE", true,
            "Match a result to a patient"),
    CLINIC_RESULT_INTERPRET(Group.RESULTS, Kind.WRITE, "CLINIC_LAB_WRITE", true,
            "Interpret a result (including AI assistance)"),
    CLINIC_RESULT_REVIEW(Group.RESULTS, Kind.SIGN, "CLINIC_LAB_WRITE", true,
            "Mark a result reviewed"),
    CLINIC_RESULT_FILE(Group.RESULTS, Kind.WRITE, "CLINIC_LAB_WRITE", true,
            "File a result to the patient record"),
    CLINIC_RESULT_ACKNOWLEDGE(Group.RESULTS, Kind.SIGN, "CLINIC_LAB_WRITE", false,
            "Acknowledge a result in the results inbox"),
    CLINIC_DOCUMENT_READ(Group.DOCUMENTS, Kind.READ, "CLINIC_READ", true,
            "View a document list"),
    CLINIC_DOCUMENT_CREATE(Group.DOCUMENTS, Kind.WRITE, "CLINIC_WRITE", true,
            "Create a document"),
    CLINIC_DOCUMENT_DOWNLOAD(Group.DOCUMENTS, Kind.READ, "CLINIC_READ", true,
            "Download a document"),
    CLINIC_DOCUMENT_PRINT(Group.DOCUMENTS, Kind.READ, "CLINIC_READ", false,
            "Print a document"),
    CLINIC_DOCUMENT_EMAIL(Group.DOCUMENTS, Kind.SEND, "CLINIC_BILLING_WRITE", true,
            "Email a document to a patient (delivery is separate from signing)"),
    CLINIC_DOCUMENT_VOID(Group.DOCUMENTS, Kind.MANAGE, "CLINIC_ADMIN", true,
            "Void a document"),
    CLINIC_CONSENT_READ(Group.CONSENT, Kind.READ, "CLINIC_READ", true,
            "View consent status"),
    CLINIC_CONSENT_HISTORY_READ(Group.CONSENT, Kind.READ, "CLINIC_READ", true,
            "View consent history"),
    CLINIC_CONSENT_RECORD(Group.CONSENT, Kind.WRITE, "CLINIC_WRITE", true,
            "Record consent"),
    CLINIC_CONSENT_UPDATE(Group.CONSENT, Kind.WRITE, "CLINIC_WRITE", false,
            "Change a consent"),
    CLINIC_CONSENT_REVOKE(Group.CONSENT, Kind.WRITE, "CLINIC_WRITE", false,
            "Revoke a consent"),
    CLINIC_RESTRICTED_RECORD_MANAGE(Group.RESTRICTED, Kind.MANAGE, null, true,
            "Flag a record or document as restricted"),
    CLINIC_RESTRICTED_RECORD_REQUEST(Group.RESTRICTED, Kind.WRITE, null, false,
            "Ask for access to a restricted record"),
    CLINIC_RESTRICTED_RECORD_ACCESS(Group.RESTRICTED, Kind.READ, null, true,
            "Open a restricted record once access is granted"),
    CLINIC_BREAK_GLASS_VIEW(Group.RESTRICTED, Kind.READ, null, true,
            "Break the glass to view a restricted record (reason required, audited, alerts the practice manager)"),
    CLINIC_BREAK_GLASS_PRINT(Group.RESTRICTED, Kind.READ, null, true,
            "Print or download a document from a restricted record opened by break-glass"),
    CLINIC_BREAK_GLASS_REVIEW(Group.RESTRICTED, Kind.MANAGE, null, true,
            "Review and acknowledge break-glass alerts (practice manager / compliance)"),
    CLINIC_BREAK_GLASS_EXPORT(Group.RESTRICTED, Kind.READ, null, true,
            "Export a restricted record opened by break-glass"),
    CLINIC_QUEUE_READ(Group.SCHEDULING, Kind.READ, "CLINIC_READ", true,
            "View the handoff queue and today's queue"),
    CLINIC_APPOINTMENT_READ(Group.SCHEDULING, Kind.READ, "CLINIC_READ", true,
            "View appointments, rooms and the waitlist"),
    CLINIC_APPOINTMENT_CREATE(Group.SCHEDULING, Kind.WRITE, "CLINIC_WRITE", true,
            "Book an appointment or add to the waitlist"),
    CLINIC_APPOINTMENT_UPDATE(Group.SCHEDULING, Kind.WRITE, "CLINIC_WRITE", true,
            "Confirm, start, complete, no-show or cancel an appointment; send reminders; work the waitlist"),
    CLINIC_APPOINTMENT_CANCEL(Group.SCHEDULING, Kind.WRITE, "CLINIC_WRITE", false,
            "Cancel an appointment (split from update when the action endpoint is split)"),
    CLINIC_APPOINTMENT_RESCHEDULE(Group.SCHEDULING, Kind.WRITE, "CLINIC_WRITE", true,
            "Reschedule an appointment"),
    CLINIC_APPOINTMENT_CHECK_IN(Group.SCHEDULING, Kind.WRITE, "CLINIC_WRITE", false,
            "Check a patient in (split from update when the action endpoint is split)"),
    CLINIC_QUEUE_MANAGE(Group.SCHEDULING, Kind.WRITE, "CLINIC_WRITE", false,
            "Manage today's queue"),
    CLINIC_PRACTITIONER_READ(Group.SCHEDULING, Kind.READ, "CLINIC_READ", true,
            "View practitioners"),
    CLINIC_PRACTITIONER_MANAGE(Group.SCHEDULING, Kind.MANAGE, "CLINIC_WRITE", true,
            "Register a practitioner"),
    CLINIC_WORKING_HOURS_WRITE(Group.SCHEDULING, Kind.WRITE, "CLINIC_WRITE", true,
            "Set a practitioner's working hours"),
    CLINIC_TIME_OFF_WRITE(Group.SCHEDULING, Kind.WRITE, "CLINIC_WRITE", true,
            "Add or cancel practitioner time off"),
    CLINIC_CLOSURE_MANAGE(Group.SCHEDULING, Kind.MANAGE, "CLINIC_ADMIN", true,
            "Create and cancel practice closures"),
    CLINIC_ROOM_MANAGE(Group.SCHEDULING, Kind.MANAGE, "CLINIC_ADMIN", true,
            "Create and edit rooms"),
    CLINIC_TELEHEALTH_ROOM_CREATE(Group.SCHEDULING, Kind.WRITE, "CLINIC_READ", true,
            "Create a video room for an appointment"),
    CLINIC_RECALL_READ(Group.SCHEDULING, Kind.READ, "CLINIC_READ", true,
            "View the recall worklist"),
    CLINIC_RECALL_MANAGE(Group.SCHEDULING, Kind.WRITE, "CLINIC_WRITE", true,
            "Log a recall action (call, snooze, dismiss)"),
    CLINIC_DASHBOARD_READ(Group.SCHEDULING, Kind.READ, "CLINIC_READ", true,
            "View the clinic dashboard"),
    CLINIC_TIMELINE_READ(Group.SCHEDULING, Kind.READ, "CLINIC_READ", true,
            "View a patient timeline"),
    CLINIC_CATALOGUE_READ(Group.SCHEDULING, Kind.READ, "CLINIC_READ", true,
            "Search the medicine and procedure catalogues"),
    CLINIC_QUESTIONNAIRE_READ(Group.SCHEDULING, Kind.READ, "CLINIC_READ", true,
            "Open questionnaires and visit-type settings used in a consultation"),
    CLINIC_QUESTIONNAIRE_ANSWER(Group.SCHEDULING, Kind.WRITE, "CLINIC_CLINICAL_WRITE", true,
            "Save questionnaire answers on a consultation"),
    CLINIC_BILL_READ(Group.BILLING, Kind.READ, "CLINIC_BILLING_READ", true,
            "View bills, statements, outstanding balances and revenue"),
    CLINIC_BILL_CREATE(Group.BILLING, Kind.WRITE, "CLINIC_BILLING_WRITE", false,
            "Create a bill"),
    CLINIC_BILL_ADJUST(Group.BILLING, Kind.MANAGE, null, false,
            "Adjust a bill (credit, discount); never granted automatically"),
    CLINIC_PAYMENT_READ(Group.BILLING, Kind.READ, "CLINIC_BILLING_READ", true,
            "View payments"),
    CLINIC_PAYMENT_CREATE(Group.BILLING, Kind.WRITE, "CLINIC_BILLING_WRITE", true,
            "Record a payment"),
    CLINIC_PAYMENT_ALLOCATE(Group.BILLING, Kind.MANAGE, null, true,
            "Allocate a scheme payment across claims, including manual override (CLINIC-DEC-006)"),
    CLINIC_PAYMENT_REVERSE(Group.BILLING, Kind.MANAGE, null, false,
            "Reverse a payment"),
    CLINIC_WRITE_OFF(Group.BILLING, Kind.MANAGE, null, true,
            "Write off a shortfall as a controlled transaction (CLINIC-DEC-001)"),
    CLINIC_CLAIM_READ(Group.BILLING, Kind.READ, "CLINIC_BILLING_READ", true,
            "View claims and claim documents"),
    CLINIC_CLAIM_CREATE(Group.BILLING, Kind.WRITE, "CLINIC_BILLING_WRITE", true,
            "Create a claim from a consultation"),
    CLINIC_CLAIM_SUBMIT(Group.BILLING, Kind.WRITE, "CLINIC_BILLING_WRITE", true,
            "Submit claims"),
    CLINIC_CLAIM_PROGRESS(Group.BILLING, Kind.WRITE, "CLINIC_BILLING_WRITE", true,
            "Move a claim through accept, reject, pay (to be split by the claims-money work)"),
    CLINIC_CLAIM_CORRECT(Group.BILLING, Kind.MANAGE, null, false,
            "Correct a submitted claim through the correction workflow (CLINIC-DEC-004)"),
    CLINIC_CLAIM_REVERSE(Group.BILLING, Kind.MANAGE, null, true,
            "Reverse or credit a claim (CLINIC-DEC-002, 003)"),
    CLINIC_CLAIM_RESUBMIT(Group.BILLING, Kind.WRITE, null, false,
            "Resubmit a corrected claim"),
    CLINIC_CONTENT_ADMIN(Group.CONTENT, Kind.MANAGE, "CLINIC_CONTENT_ADMIN", true,
            "Author question groups and visit-type settings"),
    CLINIC_CONTENT_APPROVE(Group.CONTENT, Kind.SIGN, "CLINIC_CONTENT_APPROVE", true,
            "Approve clinical content (qualified reviewer, DEC-019)"),
    CLINIC_ACCESS_LOG_READ(Group.AUDIT, Kind.READ, "CLINIC_ADMIN", true,
            "View the clinic access log"),
    ;

    public enum Group { PATIENT, CLINICAL_SUMMARY, NOTES, SCHEDULING, CONSULTATION, NURSE_WORKFLOW, PRESCRIPTION, SICK_NOTE, REFERRAL, GROWTH, RESULTS, DOCUMENTS, CONSENT, RESTRICTED, BILLING, CONTENT, AUDIT }
    /** What kind of capability: reading, changing, signing/approving, managing configuration, or sending something out. */
    public enum Kind { READ, WRITE, SIGN, MANAGE, SEND }

    /** The coarse permissions that existed before this catalogue. They are still granted and still mean what they did. */
    public static final Set<String> LEGACY = Set.of(
            "CLINIC_READ", "CLINIC_WRITE", "CLINIC_CLINICAL_WRITE", "CLINIC_CLINICAL_SIGN", "CLINIC_PRESCRIPTION_WRITE", "CLINIC_LAB_WRITE", "CLINIC_BILLING_READ", "CLINIC_BILLING_WRITE", "CLINIC_ADMIN");

    private final Group group;
    private final Kind kind;
    private final String legacy;
    private final boolean enforced;
    private final String description;

    ClinicPermission(Group group, Kind kind, String legacy, boolean enforced, String description) {
        this.group = group; this.kind = kind; this.legacy = legacy; this.enforced = enforced; this.description = description;
    }

    public String code() { return name(); }
    public Group group() { return group; }
    public Kind kind() { return kind; }
    /** The coarse permission whose holders get this one automatically, or empty when it is never granted automatically. */
    public Optional<String> legacy() { return Optional.ofNullable(legacy); }
    public boolean enforced() { return enforced; }
    public String description() { return description; }

    private static final Map<String, ClinicPermission> BY_CODE =
            Arrays.stream(values()).collect(Collectors.toUnmodifiableMap(ClinicPermission::code, p -> p));

    public static Optional<ClinicPermission> byCode(String code) { return Optional.ofNullable(BY_CODE.get(code)); }

    /** True for a code in this catalogue or one of the coarse legacy permissions. */
    public static boolean isKnown(String code) { return BY_CODE.containsKey(code) || LEGACY.contains(code); }
}
